### ISSUE TITLE
Hey 

### ISSUE THREAD

**Issue by rohankishore** [Srpboyz/Cipher#1]
This isnt exactly an issue but actually a call for collaboration. I'm also working on a text editor ide with pyqt6 but i use qscintilla. You can check my profile (its name is Aura Text). We can combine these and make a mroe powerful ide.

**Comment by Srpboyz** [comment]
Ya sure! I would be down to work together. I hope you dont mind if I continue to work on my editor while we work on yours.

**Comment by rohankishore** [comment]
Of course you can!

Thanks :)

**Comment by Srpboyz** [comment]
Do you have a discord server or anything we can use to chat about changes?

**Comment by rohankishore** [comment]
Yep.

https://discord.gg/9WUxJdTY
